version: 2.0
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:9.6-alpine

    working_directory: ~/leaflike

    steps:
      - checkout

      - restore_cache:
          keys:
            - leaflike-{{ checksum "project.clj" }}

      - run:
          name: Download dependencies
          command: lein deps
          working_directory: ~/leaflike

      - save_cache:
          key: 
            - leaflike-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER: root
        - POSTGRES_DB: leaflike_test

    working_directory: ~/leaflike

    steps:
      - run:
          name: Copy config for test
          command: cp resources/config/config.edn.test resources/config/config.edn
          working_directory: ~/leaflike

      - run:
          name: Run server tests
          command: lein test
          working_directory: ~/leaflike

workflows:
  version: 2.0
  built-and-test:
    jobs:
      - build
      - test:
          requires:
            - build